Drop `has` dependency
inspect-js/is-core-module pull request #5
Opened 2021-03-09 00:48 UTC by fregante

I noticed that `has` is only used once and the package itself depends on a 50-line sub-dependency. I think it could be dropped and replaced with about 20 characters so that `is-core-module` users won’t have to download and install 2 additional packages.

2021-03-09 01:28 UTC, ljharb requested changes
has is robust to prototype modification in a way that this is not, and in most apps, is a very common dependency used by many things - so the cost ends up being free.

2021-03-09 02:04 UTC, fregante commented
The only “rubustness” comes into play if people override Object.prototype.hasOwnProperty after this loads. If they do so before this loads, both versions are gone anyway. 

Is there any other situation I’m missing?

2021-03-09 03:07 UTC, ljharb commented
Certainly you can never defend against first-run code. However, as long as `has` is evaluated before any malicious code, it's fully robust, which is precisely what this is protecting against.

2021-03-09 03:14 UTC, fregante commented
If your app/website has code that overrides something as specific as `Object.prototype.hasOwnProperty` with something incompatible I don't think your app is very robust at all. You're saying everyone else should pay the `has` price because someone let some breaking code in their codebase.

And even then, as you confirmed this only makes it "robust" if the breaking code isn't run before that. I don't think it's worth making it worse for everyone.

2021-03-09 03:20 UTC, ljharb commented
Yes, that's right. Everyone should pay whatever price is required to ensure robustness against later-run code.

Any app that includes ads is brittle in the way you're implying, for example.

Install size is an impact close to zero; brittle code is significantly larger.

2021-03-09 03:42 UTC, ljharb commented on index.js
> +	return hasOwnProperty.call(data, x) && versionIncluded(nodeVersion, data[x]);
this will still break with `delete Function.prototype.call`.

2021-03-09 03:45 UTC, fregante commented
Closing because ES3 is so widespread it's all worth it

2021-03-09 03:45 UTC, closed without merging

2021-03-09 03:49 UTC, ljharb commented
I'm sorry you're upset, so much so that you apparently decided to block me on twitter. 12.5 million downloads a week is frankly too much usage to make any assumptions about users - if even one user still has to support ES3, it's not worth breaking them.

2021-03-09 04:30 UTC, fregante commented
> it's not worth breaking them

That's what major releases are for

2021-03-09 05:00 UTC, ljharb commented
Indeed, that would be the way to safely break them. That doesn't mean it's _worth_ breaking them, ever.

2021-08-15 19:53 UTC, jimmywarting commented
I agree with @fregante js is unfortunately the thing that slows down websites the most now days. sad but true
Only way to boost it is by reducing code/size.

[Every dependency is a potential security vulnerability](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/)

2021-08-15 20:48 UTC, ljharb commented
0.001% of the internet is over 46,000 human beings, and i will not drop support for a single person.

You can easily alter your bundler config to swap out `has` for `Object.prototype.hasOwnProperty.call` if you don't care about those people, or `Reflect.hasOwn` if you have already polyfilled it.

Separately, `Object.create` isn't going to be faster than a normal object, even if you set its prototype to `null`. You do it to avoid collisions, not because of performance.

ESM actually has JSON modules now, and you can indeed import JSON, so I think you're misinformed.

2021-08-15 20:59 UTC, jimmywarting commented
> ESM actually has JSON modules now, and you can indeed import JSON, so I think you're misinformed.

> Currently importing JSON modules are only supported in the commonjs mode and are loaded using the CJS loader. WHATWG JSON modules specification are still being standardized, and are experimentally supported by including the additional flag --experimental-json-modules when running Node.js.

2021-08-15 21:08 UTC, ljharb commented
JSON Modules is a stage 3 proposal in TC39. I'm quite familiar with the feature's progression.

However, I'm not concerned with native ESM, since it can't import CJS and since it's slower than bundling anyways.

2021-12-03 10:44 UTC, Tschrock commented
@ljharb What about these other ways to break things in this package?
```
delete String.prototype.split
delete parseInt
delete TypeError
```
Also, `has` depends on `function-bind`, which looks like it's ponyfill can broken with a later-run
```
delete Function.prototype.call
delete Function.prototype.apply
delete Array.prototype.concat
delete Object
```

As for compatability - both '.hasOwnProperty' and '.call' are already used by the `has` package, so there's no change in compatability to use them by themselves here. So the only issue is for users who have a broken object prototype because of a bad script, which will cause problems for their app regardless of what this package does.

2021-12-03 11:12 UTC, zloirock commented
@Tschrock packages like this are something like a doorway or a link farm and oriented mainly for creation traffic on other packages. You know who is the maintainer of those packages and [he is not interested in reducing its downloads](https://github.com/tarruda/has/pull/17).

![image](https://user-images.githubusercontent.com/2213682/144592896-d2c7d4de-a162-43f1-a893-d4037196acc1.png)

2021-12-03 17:32 UTC, ljharb commented
@zloirock that is slander, and if you do it again you’ll be blocked from the relevant GitHub org/repo.

2021-12-03 17:34 UTC, ljharb commented
@Tschrock yes, in an ES3 environment it’s impossible to defend against a deleted .call, but in an ES5+ environment it’s safe.

If you’ve identified a bug in this package where deleting something in ES5+ breaks it, then please file an issue. None of those are a reason to drop a dep, but the solution requires adding one (to do it properly).

2021-12-03 18:05 UTC, zloirock commented
@ljharb is that is wrong, why https://github.com/tarruda/has/pull/17 is not merged?

2021-12-03 18:10 UTC, ljharb commented
@zloirock that's a different package with a different owner.

The reasons are likely the same, though - it is supremely more competent engineering and architecture to rely on a shared dependency rather than to inline the same exact code, for maintainability purposes and a whole host of other reasons. The cost of extra bytes is worth it a thousand times over for the benefits sharing a dependency provides.

2021-12-03 18:22 UTC, zloirock commented
@ljharb this discussion about that package, you are the maintainer of that package too.

> The cost of extra bytes is worth it a thousand times over for the benefits sharing a dependency provides.

A doubtful statement. It's much better to avoid dependency and extra logic than maintain it. 4 line of obvious code is much better than 2 with the usage of 3rd party library with non-obvious logic and dependencies, that loads a hundred more lines of code and also can contain bugs.

2021-12-03 18:28 UTC, ljharb commented
Clearly we fundamentally disagree on this. Given the number of packages I maintain and the many years I've done so, I'm going to continue with my proven philosophy on every package where it's my decision. Please stop trying to argue this point with me, or on any package I own, because it's just wasting everyone's time.